### PR TITLE
Fn/update docs and travis

### LINKED ISSUE #96: Docs link is broken

### PR DESCRIPTION
**Pull request by felipenoris**
Fixes #96 .

### CODE REVIEW

**Comment by felipenoris** [comment]
Julia v1.4 don't like to test extra packages.

**Comment by felipenoris** [comment]
This is ready to review and merge.

**Comment by Tokazama** [comment]
Won't this require an ssh key for the docs to autobuild?

**Comment by felipenoris** [comment]
I don't have access to the settings from this repo, but since it has a `gh-pages` branch it looks like this is already set.

**Pull request closed without merging**
