### PR TITLE
Breaking change: Remove test facilities for downstream users

### PR DESCRIPTION
**Pull request by jakobnissen**
Right now, TranscodingStreams.jl (TS) provides test facilities in `src/testtools.jl` to be used by downstream packages. An unfortunate consequence of this is that TS now depends on Test and Random, for no good reason. (See #100) 

This change makes these dependencies test-only dependencies. Not that _this is a breaking change_, because dependencies on TS right now may use TS's test facilities in their own tests. However, this change will only break test code, not TS usage "in the wild".

### CODE REVIEW

**Comment by devmotion** [comment]
I'm wondering about what's the best way to do in a similar situation in some other packages. There we want to provide tests for an interface since downstream packages really should have access to a standardized test suite.

In your opinion, should downstream packages such as CodecLz4 construct the path to the test/testutils.jl file in their tests and include it manually (e.g., in https://github.com/JuliaIO/CodecLz4.jl/blob/092191810862b4b94fe44a939e39e1095013013f/test/frame_compression.jl#L2)? That seems a bit inconvenient for downstream packages. Maybe the package should provide some functionality for making it easier to `include` this file? But then downstream packages would still need to ensure that all required dependencies are installed.

Maybe an extension with test utilities could be an alternative (with a weak dependency on Test - or maybe that's not possible?)? Or a subpackage?

I'm mainly curious about your general opinions, I don't want to change this PR since I don't work with TranscodingStreams :slightly_smiling_face:

**Comment by ViralBShah** [comment]
We should merge this. Any reason not to at this point?

**Comment by devmotion** [comment]
FYI in AbstractFFTs we made Test a weak dependency for now, but it was not completely clear if a separate subpackage would be the better option. Hiding the test utilities in `/test` seemed not a good alternative for us since it would mean that downstream packages - which are supposed to use the test utilities - depend on the internal file structure of AbstractFFTs.

**Comment by ViralBShah** [comment]
Pinging @StefanKarpinski since he also opened #100.

**Comment by nhz2** [comment]
This was fixed by #152

**Pull request closed without merging**
