### PR TITLE
Deprecate generic `seekend` method

### PR DESCRIPTION
**Pull request by nhz2**
Ref: #183

### CODE REVIEW

**Comment by mkitti** [comment]
Use `@deprecate`.

```
help?> @deprecate
  @deprecate old new [export_old=true]

  Deprecate method old and specify the
  replacement call new, defining a new method
  old with the specified signature in the
  process.

  To prevent old from being exported, set
  export_old to false.
```

**Comment by nhz2** [comment]
I'm not sure what `new` should be in this case.

**Comment by nhz2** [comment]
Maybe it would be better not to deprecate and just remove the method in 0.11

I think the main reason for removing `seekend` is it enables things like:
Try to `seekend` and if that works use a seeking strategy, otherwise, use a streaming strategy.

Also related https://github.com/JuliaLang/julia/issues/24242

**Comment by mkitti** [comment]
Well it would nice to make this compatible with `--depwarn=true` which should default to false for normal users.

**Pull request closed without merging**
